version: "3.9"

services:
  backend:
    environment:
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
    build: .
    command: ./entrypoint.sh
    ports:
      - "80:80"
